name: Mirror to GitLab

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GPAT }}
          GITLAB_PROJECT_PATH: ${{ secrets.GITLAB_PROJECT_PATH }}
        run: |
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@gitlab.fullstackacademy.sk/${GITLAB_PROJECT_PATH}.git"
          git push --force gitlab "refs/heads/*:refs/heads/*"
          git push --force gitlab "refs/tags/*:refs/tags/*"
